<?php

namespace Swaggest\JsonSchema\Tests\PHPUnit\Spec;


use JsonSchema\Constraints\Factory;
use JsonSchema\SchemaStorage;
use JsonSchema\Validator;
use PHPUnit_Framework_TestResult;

class Draft4GeraintluffJsv4Test extends Draft4Test
{
    public function run(PHPUnit_Framework_TestResult $result = null)
    {
        return parent::run($result); // TODO: Change the autogenerated stub
    }

    /**
     * @param $schemaData
     * @param $data
     * @param $isValid
     * @param $name
     * @param $version
     * @throws \Exception
     */
    protected function runSpecTest($schemaData, $data, $isValid, $name, $version)
    {
        $error = '';

        $actualValid = \Jsv4::isValid($data, $schemaData);

        $this->assertSame($isValid, $actualValid,
            "Test: $name\n"
            . "Schema:\n" . json_encode($schemaData, JSON_PRETTY_PRINT + JSON_UNESCAPED_SLASHES)
            . "\nData:\n" . json_encode($data, JSON_PRETTY_PRINT + JSON_UNESCAPED_SLASHES)
            . "\nError: " . $error . "\n");

    }
}